baseURL = "https://jonaslieb.de/"
title = "Jonas Lieb"
theme = "hugo-coder"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true

[params]
author = "Jonas Lieb"
keywords = "blog,security,pentesting,personal"
since = 2024
colorScheme = "auto"
rtl = false
#gravatar = "lieb.jonas@gmail.com"
description =  "Jonas' personal website"
info = ["Security Professional"]
customSCSS = ["scss/custom.scss"]
customCSS = ["css/lightbox.css"]
customJS = ["js/lightbox.js"]

  
[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/jojonas/"

[[params.social]]
name = "Linkedin"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://linkedin.com/in/jonaslieb"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 6
url = "/index.xml"
rel = "alternate"
type = "application/rss+xml"

#[[menu.main]]
#name = "About"
#weight = 1
#url = "/about"

[[menu.main]]
name = "Blog"
weight = 2
url = "/blog"

#[[menu.main]]
#name = "Projects"
#weight = 3
#url = "/projects"

[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = ["'self'", "'unsafe-inline'"]
scriptsrc = ["'self'", "'unsafe-inline'"]
prefetchsrc = ["'self'"]
connectsrc = ["'self'", "https://jojonas.goatcounter.com/count"]

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
theme = nan

[permalinks]
  [permalinks.page]
    posts = '/blog/:slugorfilename/'
  [permalinks.section]
    posts = '/blog/'

[taxonomies]
  tag = 'tags'
  series = 'series'
